version: "3.8"

services:
  carnetizacion-digital-front-qa:
    container_name: carnetizacion-digital-front-qa
    build:
      context: ../../
      dockerfile: Dockerfile
      args:
        NODE_ENV: qa
        API_BASE_URL: ${API_BASE_URL}
    ports:
      - "4300:80"
    environment:
      NODE_ENV: qa
      API_BASE_URL: ${API_BASE_URL}
    restart: always
    networks:
      - network_qa

networks:
  network_qa:
