version: "3.8"

services:
  carnetizacion-digital-front-staging:
    container_name: carnetizacion-digital-front-staging
    build:
      context: ../../
      dockerfile: Dockerfile
      args:
        NODE_ENV: staging
        API_BASE_URL: ${API_BASE_URL}
    ports:
      - "4500:80"
    environment:
      NODE_ENV: staging
      API_BASE_URL: ${API_BASE_URL}
    restart: always
    networks:
      - network_staging

networks:
  network_staging:
